### PR TITLE
Initial documentation page

### PR DESCRIPTION
**Pull request by meiriv**
Initial changes in readme file

### CODE REVIEW

**Comment by ykadosh** [comment]
Welcome, @meiriv !
Thanks for the PR :)
We already have instructions for cloning/installing this repo in `CONTRIBUTING.md`...

**Comment by meiriv** [comment]
> Welcome, @meiriv !
> Thanks for the PR :)
> We already have instructions for cloning/installing this repo in [CONTRIBUTING.md](https://github.com/open-amdocs/webrix/blob/master/CONTRIBUTING.md)

take in account that most visitors will first see the content of the README which is displayed on the main page

**Comment by meiriv** [comment]
README.md should be more for users, not contributors, we should describe there the steps to install this package and use it in other projects.

**Comment by ykadosh** [comment]
Users won't need to clone & install this repo, they only need to add this package as a dependency in their project. So instructions on how to clone/install are not relevant for them, they are only relevant for contributors.

**Comment by meiriv** [comment]
> Users won't need to clone & install this repo, they only need to add this package as a dependency in their project. So instructions on how to clone/install are not relevant for them, they are only relevant for contributors.

Correct, We should have instructions how this package can be used in other projects

**Pull request closed without merging**
